// Copyright 2024 TiKV Project Authors. Licensed under Apache-2.0.

//! PCR protobuf types.
//!
//! Generated by `protobuf-build` at compile time from `proto/pcrpb/pcrpb.proto`.
//! Falls back to manual stubs when protoc is unavailable.

include!(concat!(env!("OUT_DIR"), "/mod.rs"));
